# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='gatunek',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Comment.Gatunek'),
            preserve_default=False,
        ),
    ]
