# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0002_comment_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='gatunek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comment.Gatunek', verbose_name='your text'),
        ),
    ]
