# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0003_auto_20170104_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='gatunek',
        ),
        migrations.AddField(
            model_name='utwor',
            name='gatunek',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Comment.Gatunek', verbose_name='your text'),
            preserve_default=False,
        ),
    ]
