# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0005_auto_20170104_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='utwor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Comment.Utwor'),
            preserve_default=False,
        ),
    ]
