# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0005_auto_20161121_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utwor',
            name='song',
            field=models.FileField(null=True, upload_to='music'),
        ),
    ]
