# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0006_auto_20161209_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utwor',
            name='song',
            field=models.FileField(default='kappa', upload_to=''),
            preserve_default=False,
        ),
    ]
