# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0006_lista_utwor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtwordoListy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='lista',
            name='utwor',
        ),
        migrations.AddField(
            model_name='utwordolisty',
            name='IdLista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comment.Lista'),
        ),
        migrations.AddField(
            model_name='utwordolisty',
            name='IdUtwor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comment.Utwor'),
        ),
    ]
