# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-22 20:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Comment', '0007_auto_20170119_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odsluchanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdKlient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('IdUtwor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comment.Utwor')),
            ],
        ),
        migrations.AddField(
            model_name='lista',
            name='songs',
            field=models.ManyToManyField(through='Comment.UtwordoListy', to='Comment.Utwor'),
        ),
    ]
