# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0006_auto_20161128_1541'),
        ('Comment', '0007_auto_20161209_2057'),
    ]

    operations = [
    ]
